name: Create Release and Build .deb package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Environment Setup
        id: export_env
        run: |
          echo "NAME=pathlay" >> $GITHUB_ENV
          echo "VERSION=$(echo ${{ github.ref }} | sed 's/^refs\/tags\/v//')" >> $GITHUB_ENV
          echo "OS=Ubuntu-jammy" >> $GITHUB_ENV
          echo "ARCH=amd64" >> $GITHUB_ENV

      - name: Create deb folders
        run: |
          # create DEBIAN directory if you want to add other pre/post scripts
          mkdir -p .debpkg/var/www/html/pathlay/
          mkdir -p .debpkg/DEBIAN
          cp .github/workflows/bin/postinst .debpkg/DEBIAN/postinst
          cp .github/workflows/bin/postrm .debpkg/DEBIAN/postrm
          chmod +x .debpkg/DEBIAN/postinst
          chmod +x .debpkg/DEBIAN/postrm
          cp LICENSE .debpkg/var/www/html
          cp README.md .debpkg/var/www/html
          cp -r docs/ .debpkg/var/www/html/pathlay/
          cp -r cgi-bin/ .debpkg/var/www/html/pathlay/
          cp -r css/ .debpkg/var/www/html/pathlay/
          cp -r demo_exps/ .debpkg/var/www/html/pathlay/
          cp -r javascript/ .debpkg/var/www/html/pathlay/
          cp -r pathlay_data/ .debpkg/var/www/html/pathlay/
          cp -r pathlay_users/ .debpkg/var/www/html/pathlay/
          cp -r src/ .debpkg/var/www/html/pathlay/
          cp -r db_conf.html .debpkg/var/www/html/pathlay/
          cp -r login.html .debpkg/var/www/html/pathlay/
          cp -r pathlayHome.html .debpkg/var/www/html/pathlay/
          cp -r pathlay_demo.html .debpkg/var/www/html/pathlay/
          cp -r welcome.html .debpkg/var/www/html/pathlay/
          chmod +x .debpkg/var/www/html/pathlay/cgi-bin/*.pl


      - uses: jiro4989/build-deb-action@v3
        with:
          package: ${{ env.NAME }}
          package_root: .debpkg
          maintainer: 'Lorenzo Casbarra <lorenzo.casbarra@gmail.com>, Matteo Ramazzotti <matteo.ramazzotti@unifi.it>'
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'amd64'
          depends: 'apache2 (>=2.4.52-1ubuntu4.8), apache2-utils (>= 2.4.52-1ubuntu4.8), cpanminus (>= 1.7045-1), libcanberra-gtk-module:amd64 (>= 0.30-10ubuntu1.22.04.1), libexpat1-dev:amd64 (>= 2.4.7-1ubuntu0.3), libgd-dev:amd64 (>= 2.3.0-2ubuntu2), libgtk2.0-0:amd64 (>= 2.24.33-2ubuntu2), liblocal-lib-perl (>= 2.000028-1), libssl-dev:amd64 (>= 3.0.2-0ubuntu1.15), packagekit-gtk3-module (>= 1.2.5-2ubuntu2), tar (>= 1.34+dfsg-1ubuntu0.1.22.04.2), tcl (>= 8.6.11+1build2), zip (>= 3.0-12build2), librsvg2-bin (>= 2.52.5+dfsg-3ubuntu0.2)'
          desc: 'PathLay\nA graphical pathway-based platform for the interpretation of multi-omics studies\nPlease read the documentation at https://pathlay.readthedocs.io/en/latest/'

      - name: Rename Files
        id: rename_files
        run: |
         mv *.deb ${{ env.NAME }}_${{ env.VERSION }}_${{ env.OS }}_${{ env.ARCH }}.deb        
         ls -ltra

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false
  

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.NAME }}_${{ env.VERSION }}_${{ env.OS }}_${{ env.ARCH }}.deb
          asset_name: ${{ env.NAME }}_${{ env.VERSION }}_${{ env.OS }}_${{ env.ARCH }}.deb
          asset_content_type: application/octet-stream
  